# Site wide configuration

title: "Chichinabo.org"
description: "We share Small Data for analyzing Big Data."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Benito Zaragozí"
  web: "http://www.benito-zaragozi.com"
  twitter: "benizar81"
  bio: "Geographer and GIScientist."
  avatar: "bio-photo.jpg" # 160x160 px image for author byline
  google:
    plus:
    ad-client:
    ad-slot:
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
